### ISSUE TITLE
Error on Launch after Successful Install

### ISSUE THREAD

**Issue by Pepperberry-Interactive** [NBZion/SteamModDownloader#7]
Running `./smd launch` (after `./smd install` without any issues) yields the following:

```
Traceback (most recent call last):
  File "/home/pepperberry/Content/Modifier Software/SteamModDownloader/__main__.py", line 1, in <module>
    from scripts.init import start
  File "/home/pepperberry/Content/Modifier Software/SteamModDownloader/scripts/init.py", line 6, in <module>
    from tkinter import Tk
  File "/usr/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```

I'm currently running Arch Linux. For the sake of brevity, here's what `./smd install` outputted:

```
[WARN] This action will download SMD in your local directory.
[PROMPT] (Press CTRL+C to quit, or ENTER to continue) 
Cloning into 'SteamModDownloader'...
remote: Enumerating objects: 225, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 225 (delta 63), reused 62 (delta 53), pack-reused 146 (from 1)
Receiving objects: 100% (225/225), 42.76 KiB | 1.71 MiB/s, done.
Resolving deltas: 100% (131/131), done.
Collecting beautifulsoup4==4.11.0 (from -r requirements.txt (line 1))
  Downloading beautifulsoup4-4.11.0-py3-none-any.whl.metadata (3.5 kB)
Collecting requests==2.28.1 (from -r requirements.txt (line 2))
  Downloading requests-2.28.1-py3-none-any.whl.metadata (4.6 kB)
Collecting wget==3.2 (from -r requirements.txt (line 3))
  Downloading wget-3.2.zip (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting soupsieve>1.2 (from beautifulsoup4==4.11.0->-r requirements.txt (line 1))
  Downloading soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<3,>=2 (from requests==2.28.1->-r requirements.txt (line 2))
  Downloading charset_normalizer-2.1.1-py3-none-any.whl.metadata (11 kB)
Collecting idna<4,>=2.5 (from requests==2.28.1->-r requirements.txt (line 2))
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<1.27,>=1.21.1 (from requests==2.28.1->-r requirements.txt (line 2))
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
Collecting certifi>=2017.4.17 (from requests==2.28.1->-r requirements.txt (line 2))
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading beautifulsoup4-4.11.0-py3-none-any.whl (71 kB)
Downloading requests-2.28.1-py3-none-any.whl (62 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading soupsieve-2.6-py3-none-any.whl (36 kB)
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
Building wheels for collected packages: wget
  Building wheel for wget (pyproject.toml) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=8a58a4d29753778666034562ae32c99a9f8e0e2ab3316c8b9b78cfeb06a75595
  Stored in directory: /home/pepperberry/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget
Installing collected packages: wget, urllib3, soupsieve, idna, charset-normalizer, certifi, requests, beautifulsoup4
Successfully installed beautifulsoup4-4.11.0 certifi-2024.8.30 charset-normalizer-2.1.1 idna-3.10 requests-2.28.1 soupsieve-2.6 urllib3-1.26.20 wget-3.2

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python3 -m pip install --upgrade pip
[SUCCESS] You can now launch SMD.
```

**Comment by NBZion** [comment]
I can work on a fix on this. I'll work on this ASAP it's currently 10 22 pm rn and I have to be up tomorrow so just wait!!!

**Comment by NBZion** [comment]
For now you can open conf.json and input the mod folder manually instead!

**Comment by NBZion** [comment]
I pushed a fix just right now! can you test if it works now?

**Comment by NBZion** [comment]
Since this issue inactive, i'll assume this issue is resolved!
